apiVersion: {{ template "deployment_api_version" . }}
kind: Deployment
metadata:
  name: {{ template "app.nginx.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      chart: {{ template "app.version" . }}
      release: {{ .Release.Name }}
      component: nginx
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ template "app.version" . }}
        release: {{ .Release.Name }}
        component: nginx
    spec:
      {{- if .Values.enabledRBAC }}
      serviceAccountName: {{ default (default (include "app.fullname" .) .Values.serviceAccountName) .Values.serviceAccountNameOverride }}
      {{- end }}
      initContainers:
      - name: nginx-init-auth-add
        image: {{ .Values.image.auth.repository }}:{{ .Values.image.auth.tag }}
        command:
        - /usr/bin/replace-config-by-auth.sh
        volumeMounts:
        - name: prometheus-static-hooks
          mountPath: /usr/bin/replace-config-by-auth.sh
          subPath: replace-config-by-auth.sh
        - name: prometheus-static-contents
          mountPath: /host
        - name: prometheus-nginx-template
          mountPath: /template
        {{- if and .Values.resources .Values.resources.inits }}
        resources:
{{ toYaml .Values.resources.inits | indent 10 }}
        {{- end }}
      containers:
      - name: prometheus-proxy
        image: {{ .Values.image.proxy.repository }}:{{ .Values.image.proxy.tag }}
        args:
        - nginx
        - -g
        - daemon off;
        - -c
        - /nginx/nginx.conf
        volumeMounts:
        - mountPath: /nginx
          name: prometheus-static-contents
        {{- if and .Values.resources .Values.resources.proxy }}
        resources:
{{ toYaml .Values.resources.proxy | indent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      volumes:
      - name: prometheus-static-hooks
        configMap:
          name: {{ template "app.hooks.fullname" . }}
          defaultMode: 0777
      - name: prometheus-static-contents
        emptyDir: {}
      - name: prometheus-nginx-template
        configMap:
          name: {{ template "app.nginx.fullname" . }}
          defaultMode: 438
          items:
          - key: nginx.conf
            mode: 438
            path: nginx.conf
