apiVersion: {{ template "operator_api_version" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    {{- if .Values.serviceMonitor.labels }}
{{ toYaml .Values.serviceMonitor.labels | indent 4 }}
    {{- end }}
  name: {{ template "app.fullname" . }}
spec:
  jobLabel: prometheus
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      chart: {{ template "app.version" . }}
      release: {{ .Release.Name }}
      {{ .Values.apiGroup }}: "true"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: http
    interval: 30s
{{- if eq .Values.level "cluster" }}
---
apiVersion: {{ template "operator_api_version" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    {{- if .Values.serviceMonitor.labels }}
{{ toYaml .Values.serviceMonitor.labels | indent 4 }}
    {{- end }}
  name: {{ include "app.auth.fullname" . }}
spec:
  jobLabel: prometheus-auth
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      chart: {{ template "app.version" . }}
      release: {{ .Release.Name }}
      component: auth
      {{ .Values.apiGroup }}: "true"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: http
    interval: 15s
    path: /_/metrics
{{- end }}
