{
 "title": "Rancher Components",
 "description": "This is a simple dashboard for: https://github.com/banzaicloud/logging-operator utilising Fluent-bit and Fluentd",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Active Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\"})"
    }
   ]
  },
  {
   "title": "Fluentd",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{pod=~\"fluentd.*\"})"
    }
   ]
  },
  {
   "title": "Fluent input records",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_input_status_num_records_total[1m]))by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Fluentd output buffer queue length",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_buffer_queue_length[1m])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Fluentd output error/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_num_errors[1m])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Fluentd output emit/s by Plugin",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_emit_count[1m])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Fluentd output buffer queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_queue_length",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Fluentd retries/rollback",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentd_output_status_retry_count[1m])",
     "legendFormat": "Retries {{ type }}"
    },
    {
     "expr": "rate(fluentd_output_status_rollback_count[1m])",
     "legendFormat": "Rollback {{ type }}"
    }
   ]
  },
  {
   "title": "Fluentd output error/retry rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_retry_count[1m]))",
     "legendFormat": "Retry rate"
    },
    {
     "expr": "sum(rate(fluentd_output_status_num_errors[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Fluentd output buffer size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_total_bytes",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}