apiVersion: v1
kind: Service
metadata:
  name: expose-kubernetes-metrics
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{ .Values.apiGroup }}: "true"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    release: {{ .Release.Name }}
  ports:
  - name: metrics
    port: {{ .Values.ports.metrics.port }}
    targetPort: 8080
    protocol: TCP
